export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_PROFESORS = 'GET_PROFESORS';
export const GET_MATERIAS = 'GET_MATERIAS';
export const GET_MATERIAS_BY_ID = 'GET_MATERIAS_BY_ID';
export const GET_MATERIAS_BY_NAME = 'GET_MATERIAS_BY_NAME';
export const CLEAN_DETAIL = 'CLEAN_DETAIL'; 
export const POST_ALUMNO = 'POST_ALUMNO';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS'
export const VERIFY_USER_ERROR = 'VERIFY_USER_ERROR'

