export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_PROFESORS = 'GET_PROFESORS';
export const GET_MATERIAS = 'GET_MATERIAS';
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const CLEAR_USER_ROLE = 'CLEAR_USER_ROLE';